# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UDAFQQm4iThPyynvW5PLjWS9VPV9-Utg
"""

# app.py
import streamlit as st
import pandas as pd
import pickle
import numpy as np

# Page configuration
st.set_page_config(page_title="Churn Prediction System", page_icon="📊")

# Load trained model
@st.cache_resource
def load_model():
    with open("churn_model.pkl", "rb") as file:
        model = pickle.load(file)
    return model

model = load_model()

st.title("📊 Customer Churn Prediction System")
st.write("Predict whether a customer is likely to churn based on their service details.")

# Sidebar for input
st.sidebar.header("Enter Customer Details")

# Numerical columns
num_cols = ['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']
num_data = {}
for col in num_cols:
    num_data[col] = st.sidebar.number_input(f"{col}", min_value=0.0, step=1.0)

# Categorical columns and their options
cat_options = {
    'gender': ['Male', 'Female'],
    'Partner': ['Yes', 'No'],
    'Dependents': ['Yes', 'No'],
    'PhoneService': ['Yes', 'No'],
    'MultipleLines': ['Yes', 'No', 'No phone service'],
    'InternetService': ['DSL', 'Fiber optic', 'No'],
    'OnlineSecurity': ['Yes', 'No', 'No internet service'],
    'OnlineBackup': ['Yes', 'No', 'No internet service'],
    'DeviceProtection': ['Yes', 'No', 'No internet service'],
    'TechSupport': ['Yes', 'No', 'No internet service'],
    'StreamingTV': ['Yes', 'No', 'No internet service'],
    'StreamingMovies': ['Yes', 'No', 'No internet service'],
    'Contract': ['Month-to-month', 'One year', 'Two year'],
    'PaperlessBilling': ['Yes', 'No'],
    'PaymentMethod': ['Electronic check', 'Mailed check', 'Bank transfer (automatic)', 'Credit card (automatic)']
}

cat_data = {}
for col, options in cat_options.items():
    cat_data[col] = st.sidebar.selectbox(f"{col}", options=options)

# Combine numerical and categorical input
input_data = {**num_data, **cat_data}
input_df = pd.DataFrame([input_data])

st.subheader("🔍 Input Summary")
st.dataframe(input_df)

# Predict churn
if st.button("Predict Churn"):
    prediction = model.predict(input_df)
    probability = model.predict_proba(input_df)[:, 1][0]

    if prediction[0] == 1:
        st.error(f"⚠️ Customer is likely to **CHURN**.")
    else:
        st.success(f"✅ Customer is likely to **STAY**.")
    st.write(f"**Churn Probability:** {probability:.2f}")

st.markdown("---")
st.caption("Developed by Vignesh L V | Future Interns – Machine Learning Task 2")